In [1]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'Name': ['Rishi','kinjal','hardyansh','mohit'],
    'age' : [20,19,19,19],
    'city': ['jodhpur','chitorgarh','bikaner','paota'],
    'Salary': [100000,90000,50000,50000]
}
df = pd.DataFrame(data)
df

        Name  age        city  Salary
0      Rishi   20     jodhpur  100000
1     kinjal   19  chitorgarh   90000
2  hardyansh   19     bikaner   50000
3      mohit   19       paota   50000

In [38]:
data_list = [
    ['rishi',20,'Jodhpur',100000],
    ['kinjal',19,'chittorgarh',90000],
    ['hardyansh',19,'bikaner',60000],
    ['mohit',19,'paota',50000]
]   
df2 = pd.DataFrame (data_list)
columns = ["name","age","city","salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

        name  age         city  salary
0      rishi   20      Jodhpur  100000
1     kinjal   19  chittorgarh   90000
2  hardyansh   19      bikaner   60000
3      mohit   19        paota   50000

In [16]:
df2.head()

           0   1            2       3
0      rishi  20      Jodhpur  100000
1     kinjal  19  chittorgarh   90000
2  hardyansh  19      bikaner   60000
3      mohit  19        paota   50000

In [17]:
df2.head(2)

        0   1            2       3
0   rishi  20      Jodhpur  100000
1  kinjal  19  chittorgarh   90000

In [18]:
df2.tail()

           0   1            2       3
0      rishi  20      Jodhpur  100000
1     kinjal  19  chittorgarh   90000
2  hardyansh  19      bikaner   60000
3      mohit  19        paota   50000

In [19]:
df2.tail(2)

           0   1        2      3
2  hardyansh  19  bikaner  60000
3      mohit  19    paota  50000

In [40]:
df.shape

(4, 4)

In [23]:
df2.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
df2.columns

RangeIndex(start=0, stop=4, step=1)

In [41]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
df.columns.tolist()

['Name', 'age', 'city', 'Salary']

In [29]:
df.columns

Index(['Name', 'age', 'city', 'Salary'], dtype='str')

In [30]:
df.dtypes

Name        str
age       int64
city        str
Salary    int64
dtype: object

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   age     4 non-null      int64
 2   city    4 non-null      str
 3   Salary  4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [33]:
df.describe()

         age         Salary
count   4.00       4.000000
mean   19.25   72500.000000
std     0.50   26299.556397
min    19.00   50000.000000
25%    19.00   50000.000000
50%    19.00   70000.000000
75%    19.25   92500.000000
max    20.00  100000.000000

In [34]:
df['Name']

0        Rishi
1       kinjal
2    hardyansh
3        mohit
Name: Name, dtype: str

In [ ]:
df[[Name,salary]]

NameError: name 'Name' is not defined

In [43]:
df[['Name','Salary']]

        Name  Salary
0      Rishi  100000
1     kinjal   90000
2  hardyansh   50000
3      mohit   50000

In [ ]:
selection and indexing of columns

In [46]:
df['Name']

0        Rishi
1       kinjal
2    hardyansh
3        mohit
Name: Name, dtype: str

In [47]:
df[['Name','city']]

        Name        city
0      Rishi     jodhpur
1     kinjal  chitorgarh
2  hardyansh     bikaner
3      mohit       paota

In [49]:
creating a new column

SyntaxError: invalid syntax (1622062636.py, line 1)

In [50]:
df["Designation"] = ['Ceo','cfo','cmo','coo']

In [51]:
df

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo
3      mohit   19       paota   50000         coo

In [ ]:
remove a column

In [53]:
df.drop('age',axis=1)

        Name        city  Salary Designation
0      Rishi     jodhpur  100000         Ceo
1     kinjal  chitorgarh   90000         cfo
2  hardyansh     bikaner   50000         cmo
3      mohit       paota   50000         coo

In [54]:
df

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo
3      mohit   19       paota   50000         coo

In [58]:
df.drop(["city","age"],axis=1)

        Name  Salary Designation
0      Rishi  100000         Ceo
1     kinjal   90000         cfo
2  hardyansh   50000         cmo
3      mohit   50000         coo

In [59]:
df

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo
3      mohit   19       paota   50000         coo

In [60]:
df.drop(2,axis=0)

     Name  age        city  Salary Designation
0   Rishi   20     jodhpur  100000         Ceo
1  kinjal   19  chitorgarh   90000         cfo
3   mohit   19       paota   50000         coo

In [61]:
df.drop(3,axis=0)

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo

In [63]:
df.loc[[0,1]]

     Name  age        city  Salary Designation
0   Rishi   20     jodhpur  100000         Ceo
1  kinjal   19  chitorgarh   90000         cfo

In [66]:
df.iloc[0]

Name             Rishi
age                 20
city           jodhpur
Salary          100000
Designation        Ceo
Name: 0, dtype: object

In [ ]:
SELECTING SUBSET ROWS AND COLUMNS

In [68]:
df.loc[[0,1]][["city","Salary"]]

         city  Salary
0     jodhpur  100000
1  chitorgarh   90000

In [71]:
df.loc[[2,3]][["Name","age"]]

        Name  age
2  hardyansh   19
3      mohit   19

In [70]:
df

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo
3      mohit   19       paota   50000         coo

In [ ]:
CONDITIONAL SELECTIONS

In [75]:
df[df["age"]>=20]

    Name  age     city  Salary Designation
0  Rishi   20  jodhpur  100000         Ceo

In [82]:
df2[(df2["age"] >= 19) & (df2["city"] == "Jodhpur")]

    name  age     city  salary
0  rishi   20  Jodhpur  100000

In [ ]:
df

        Name  age        city  Salary Designation
0      Rishi   20     jodhpur  100000         Ceo
1     kinjal   19  chitorgarh   90000         cfo
2  hardyansh   19     bikaner   50000         cmo
3      mohit   19       paota   50000         coo