In [1]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'Name': ['Rishi','kinjal','hardyansh','mohit'],
    'age' : [20,19,19,19],
    'city': ['jodhpur','chitorgarh','bikaner','paota'],
    'Salary': [100000,90000,50000,50000]
}
df = pd.DataFrame(data)
df

        Name  age        city  Salary
0      Rishi   20     jodhpur  100000
1     kinjal   19  chitorgarh   90000
2  hardyansh   19     bikaner   50000
3      mohit   19       paota   50000

In [15]:
data_list = [

    ['rishi',20,'Jodhpur',100000],
    ['kinjal',19,'chittorgarh',90000],
    ['hardyansh',19,'bikaner',60000],
    ['mohit',19,'paota',50000]
]   
df2 = pd.DataFrame (data_list)
df2

           0   1            2       3
0      rishi  20      Jodhpur  100000
1     kinjal  19  chittorgarh   90000
2  hardyansh  19      bikaner   60000
3      mohit  19        paota   50000