In [2]:
import numpy as np
import pandas as pd

In [3]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    "Name": ['rishi','hardyansh','mohit','kinjal',"Lokesh"],
    "daprtment": ["IT",'HR','FINANCE','IT','HR'],
})


salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [4]:
employees

   employee_id       Name daprtment
0            1      rishi        IT
1            2  hardyansh        HR
2            3      mohit   FINANCE
3            4     kinjal        IT
4            5     Lokesh        HR

In [5]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
merge 2 data frames

In [6]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [7]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id       Name daprtment  salary  bonus
0            1      rishi        IT   60000   5000
1            2  hardyansh        HR   80000  10000
2            3      mohit   FINANCE   65000   7000

In [9]:
pd.merge(employees,salaries, on="employee_id",how="outer")

   employee_id       Name daprtment   salary    bonus
0            1      rishi        IT  60000.0   5000.0
1            2  hardyansh        HR  80000.0  10000.0
2            3      mohit   FINANCE  65000.0   7000.0
3            4     kinjal        IT      NaN      NaN
4            5     Lokesh        HR      NaN      NaN
5            6        NaN       NaN  70000.0   8000.0
6            7        NaN       NaN  90000.0  12000.0

In [10]:
pd.DataFrame([10,23,345])

     0
0   10
1   23
2  345

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="right") on the basis of the salaries

   employee_id       Name daprtment  salary  bonus
0            1      rishi        IT   60000   5000
1            2  hardyansh        HR   80000  10000
2            3      mohit   FINANCE   65000   7000
3            6        NaN       NaN   70000   8000
4            7        NaN       NaN   90000  12000

In [13]:
pd.merge(employees,salaries,on="employee_id",how="left")

   employee_id       Name daprtment   salary    bonus
0            1      rishi        IT  60000.0   5000.0
1            2  hardyansh        HR  80000.0  10000.0
2            3      mohit   FINANCE  65000.0   7000.0
3            4     kinjal        IT      NaN      NaN
4            5     Lokesh        HR      NaN      NaN

In [ ]:
Concatination of Two Frames

In [14]:
df1 = pd.DataFrame(
    {
        'A':['A0','A1','A2'],
        'B':['B0','B1','B2'],
        'C':['c1','c2','c3']
    }
)
df2 = pd.DataFrame({
    'A':["A4","A5","A6"],
    'B':["B4","B5","B6"],
    'C':["C4","C5","C6"]
})

In [15]:
df1

    A   B   C
0  A0  B0  c1
1  A1  B1  c2
2  A2  B2  c3

In [16]:
df2

    A   B   C
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6

In [17]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  c1
1  A1  B1  c2
2  A2  B2  c3
0  A4  B4  C4
1  A5  B5  C5
2  A6  B6  C6

In [19]:
pd.concat([df1,df2], 
          axis= 1)

    A   B   C   A   B   C
0  A0  B0  c1  A4  B4  C4
1  A1  B1  c2  A5  B5  C5
2  A2  B2  c3  A6  B6  C6

In [ ]:
JOINING 2 DATAFRAMES

In [21]:
df1 = pd.DataFrame({
    'Name':['Alice','bob','Charlie']
},index=[1,2,3])

df2 = pd.DataFrame({
    'Score':[89,76,88]
},index=[2,3,4])

In [22]:
df1

      Name
1    Alice
2      bob
3  Charlie

In [23]:
df2

   Score
2     89
3     76
4     88

In [24]:
df1.join(df2,how="outer")

      Name  Score
1    Alice    NaN
2      bob   89.0
3  Charlie   76.0
4      NaN   88.0

In [25]:
df2.join(df1)

   Score     Name
2     89      bob
3     76  Charlie
4     88      NaN