In [1]:
import numpy as np
import pandas as pd

In [ ]:
finding missing data

In [5]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [6]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [8]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [9]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
removing missing data

In [10]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [11]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [13]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [14]:
thresh = 4 means rows ke andar utni non null value present honi chaiye

SyntaxError: invalid syntax (2758458878.py, line 1)

FILLING THE MISSING DATA

In [16]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [ ]:
these are nto permanaent for make it permanent do it inplace=True

In [17]:
values = {'A':0,'B':100,'C':200,'D':300}

In [18]:
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  300.0
2  0.0    3.0    3.0  300.0
3  4.0    4.0  200.0  300.0
4  5.0    5.0  200.0    5.0

In [ ]:
FILLING IS DONE USING COLUMN WISE AND REMOVING IS USING ROW WISE

In [19]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [21]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0